version: "3"
services:
    tests:
      image: "./todo-app/tests/Dockerfile"
      depends_on:
        - "back-end"
        - "front-end"
      environment:
        - FRONT_HOST=todofrontend
    front-end:
      image: "./todo-app/front-end/Dockerfile"
      ports:
        - 3000
      environment:
        - REACT_APP_API_HOST=todobackend
      depends_on:
        - "back-end"
    back-end:
      image: "./todo-app/back-end/Dockerfile"
      ports:
        - 3001