version: '3'
services:
    tests:
      image: todotests
      depends_on:
        - "todobackend"
        - "todofront"
      environment:
        - FRONT_HOST=todofront
    todofront:
      image: todofrontend
      ports:
        - 3000:3000
      environment:
        - REACT_APP_API_HOST=todoback
      depends_on:
        - "todobackend"
    todobackend:
      image: todobackend
      ports:
        - 3001:3001