version: "3"
services:
    tests:
      build: ./todo-app/tests
      depends_on:
        - "back-end"
        - "front-end"
      environment:
        - FRONT_HOST=todofrontend
    front-end:
      build: ./todo-app/front-end
      ports:
        - 3000
      environment:
        - REACT_APP_API_HOST=todobackend
      depends_on:
        - "back-end"
    back-end:
      build: ./todo-app/back-end
      ports:
        - 3001