version: "3"
services:
    tests:
      image: todotests
      depends_on:
        - "back-end"
        - "front-end"
      environment:
        - FRONT_HOST=todofrontend
    front-end:
      image: todofrontend
      ports:
        - 3000
      environment:
        - REACT_APP_API_HOST=todobackend
      depends_on:
        - "back-end"
    back-end:
      image: todobackend
      ports:
        - 3001